[FEAT/#6] like / 저장 탭 구현 완료
Keyneez/Keyneez-AOS pull request #16
Opened 2023-01-04 11:50 UTC by 0zlrlo

## 관련 이슈
- closed #6 

## 작업 내역
-저장 탭 UI 수정
-저장 탭 코드 구현

## PR 포인트
- 리사이클러뷰 UI 관련하여 약간 수정하였습니다!
- coil로 이미지 뜨게끔 코드 짜 보았습니다.
- 이미지 모서리(코너)가 라운드되게끔 코드 짠 부분 참고하시면 좋을 것 같습니다.
- 저장버튼 누르면 상단으로 올라가게 됩니다.

## 실행 화면
<img width="363" alt="스크린샷 2023-01-04 오후 8 49 59" src="https://user-images.githubusercontent.com/99941493/210549001-cab3d3ca-e36a-49c1-8bbc-57f7153a5bec.png">

2023-01-04 15:45 UTC, b1urrrr requested changes
고생하셨습니다!!

2023-01-04 15:45 UTC, b1urrrr commented on app/src/main/java/com/keyneez/presentation/main/like/LikeAdapter.kt
> +class LikeAdapter : RecyclerView.Adapter<LikeAdapter.getViewHolder>() {
나중에 여유가 된다면 ListAdapter로 구현해봐도 좋을 것 같습니다.

2023-01-04 15:45 UTC, b1urrrr commented on app/src/main/java/com/keyneez/presentation/main/like/LikeFragment.kt
> +            // 어댑터에서 mutablelist썼으면 뷰홀더에서도 mutablelist를 사용하고 어댑터에서 listOf를 썼으면 뷰홀더에서도 통일하기
프로젝트 리포지토리에서는 주석을 적재적소에 써주세요!
굳이 없어도 되는 주석처럼 보입니다!

2023-01-04 15:45 UTC, b1urrrr commented on app/src/main/java/com/keyneez/presentation/main/like/LikeFragment.kt
> +    }
`setOnClickListener` 대신 `setOnSingleClickListener`를 사용해주세요.

2023-01-04 15:45 UTC, b1urrrr commented on app/src/main/java/com/keyneez/presentation/main/like/LikeViewModel.kt
> +        // 코틀린은 자동적으로 타입을 추론해 주기 때문에 굳이 타입을 안 써줘도 된다.
주석 지워주시는 게 보기 편할 것 같습니다!

2023-01-04 15:45 UTC, b1urrrr commented on app/src/main/res/layout/item_like_content.xml
> +            android:background="@drawable/shape_14_rect"
coil로 둥근 모서리를 설정해주면 drawable 파일은 지우고 background 속성도 지우면 될 것 같아요!

2023-01-04 15:45 UTC, b1urrrr commented on app/src/main/java/com/keyneez/presentation/main/like/LikeAdapter.kt
> +            }
coil 사용 굿굿입니다!! 👏👏👏

2023-01-04 17:23 UTC, b1urrrr approved these changes
LGTM 👍👍

2023-01-05 04:12 UTC, l2hyunwoo commented
👍🏻

2023-01-05 06:37 UTC, DongjooSEO approved these changes
에고 확인이 늦었다ㅠ
고생해써!!❤

2023-01-05 06:47 UTC, merged