[UI/#14] onboarding 뷰 레이아웃 구현
Keyneez/Keyneez-AOS pull request #19
Opened 2023-01-05 10:36 UTC by DongjooSEO

## 관련 이슈
- closed #14 

## 작업 내역
-온보딩 뷰 레이아웃 구현
- dot indicator (https://github.com/tommybuonomo/dotsindicator)와 뷰페이저 연결

## PR 포인트
- 일단 뷰만 완성
- 뷰페이저 4번째 프래그먼트 일시 로그인, 회원가입 버튼이 생기는 건 어떻게 구현하는 게 좋을 지 고민 중입니다💦

## 실행 화면

2023-01-05 12:51 UTC, b1urrrr requested changes
온보딩 구현하시느라 고생하셨습니다!!
dot indicator는 처음 보는데 너무 예쁘네요 🥰

2023-01-05 12:51 UTC, b1urrrr commented on app/src/main/java/com/keyneez/presentation/onboarding/OnFirstFragment.kt
> +}
모든 Fragment에 `newInstance()` 함수 넣어주시면 좋을 것 같아요!

2023-01-05 12:51 UTC, b1urrrr commented on app/src/main/java/com/keyneez/presentation/onboarding/OnboardingActivity.kt
> +        }
3 페이지일 때도 로그인 회원가입 버튼이 안 나타나는 것 같네요!
그리고 3 페이지에서 2 페이지로 돌아갔을 때 버튼이 invisible 처리가 되도록 로직을 짜야 할 것 같습니다.
(방법은 많겠지만 databinding을 사용하면 쉽게 처리할 수 있을 것 같아 보이네요.)

2023-01-05 12:51 UTC, b1urrrr commented on app/src/main/java/com/keyneez/presentation/onboarding/adapter/OnVPAdapter.kt
> +    }
저는 리스트로 처리했었는데 when문으로 바꿔야겠어요!
이렇게 하니까 가독성이 더 좋은 것 같네요 🤭

2023-01-05 12:51 UTC, b1urrrr commented on app/src/main/res/drawable/img_onboarding_logoa.xml
> +  <path
혹시 logo'a'는 오타일까요?

2023-01-05 12:51 UTC, b1urrrr commented on app/src/main/res/drawable/shape_gray050_gary900line_4_rect.xml
> +        android:height="48dp" />
shape drawable은 공용으로 재사용할 수 있기 때문에 size 속성은 빼주세요!
그리고 dp값 지정은 최대한 지양해주세요! 
(대신 레이아웃 xml에서 wrap_content를 활용해주시면 될 것 같습니다.)

2023-01-05 12:51 UTC, b1urrrr commented on app/src/main/res/drawable/shape_gray050_gary900line_4_rect.xml
> +
같은 이유로 padding도 빼주시는 게 좋을 것 같습니다.
밑에 빈 줄어 없애주세요!

2023-01-05 12:51 UTC, b1urrrr commented on app/src/main/res/drawable/shape_gray050_gary900line_4_rect.xml
> +</shape>
shape_gray050_fill_gray900_line_4_rect.xml
이렇게 네이밍 하는 게 좋을 것 같습니다!

2023-01-05 12:51 UTC, b1urrrr commented on app/src/main/res/drawable/shape_gray900_fill_4_rect.xml
> +</shape>
같은 이유로 size와 padding 속성은 빼주세요!

2023-01-05 12:51 UTC, b1urrrr commented on app/src/main/res/layout/activity_main.xml
> +            android:src="@drawable/ic_main_card_up"
감삼다 ❤️

2023-01-05 12:51 UTC, b1urrrr commented on app/src/main/res/layout/activity_onboarding.xml
> +            android:layout_height="48dp"
height도 wrap_content로 하면 안 될까요?
dp값을 주지 않는 방법을 찾아봅시다!

2023-01-05 12:51 UTC, b1urrrr commented on app/src/main/res/layout/activity_onboarding.xml
> +            app:layout_constraintTop_toBottomOf="@id/vp_onboarding" />
dot indicator 애니메이션 넘 예쁘네요!

2023-01-05 12:51 UTC, b1urrrr commented on app/build.gradle
> +    //dot indicator
```suggestion
    // dot indicator
```

별 거 아니지만 ktlint 문법대로 주석을 써봅시다 🙃

2023-01-05 13:14 UTC, b1urrrr commented on app/src/main/java/com/keyneez/presentation/onboarding/adapter/OnVPAdapter.kt
> +class OnVPAdapter(fragmentActivity: FragmentActivity) : FragmentStateAdapter(fragmentActivity) {
흠 RV(리사이클러뷰), VP(뷰페이저) 붙이지 않고 네이밍을 OnboardingAdapter로 해도 괜찮을 것 같은데 어떤가요?

2023-01-05 13:14 UTC, b1urrrr commented on app/src/main/java/com/keyneez/presentation/onboarding/adapter/OnVPAdapter.kt
> +    }
when문으로 처리하는 게 더 가독성 있어 보였는데.. 코드를 짜보니까 리스트로 처리하는 게 하드코딩이나 오류를 방지할 수 있을 것 같네요! 한번 OcrGuideAdapter를 참고해서 리스트로 처리해보시는 걸 추천 드립니다!

2023-01-05 13:24 UTC, b1urrrr commented
그리고 AndroidManifest.xml에 onboarding 액티비티를 추가해야할 것 같습니다!!
실행은 어떻게 하신거죠....?! ㅋㅋㅋㅋㅋㅋ

2023-01-05 13:29 UTC, b1urrrr commented on app/src/main/java/com/keyneez/presentation/onboarding/OnboardingActivity.kt
> +        }
현재 currentItem이 3일 때 버튼이 나타나지 않는 이유는 이 로직이 OnboardingActivity가 생성되었을 때 한번만 실행되고 있기 때문입니다

2023-01-05 15:07 UTC, 0zlrlo approved these changes

2023-01-05 15:07 UTC, 0zlrlo commented on app/src/main/java/com/keyneez/presentation/onboarding/adapter/OnVPAdapter.kt
> +    }
채연언니가 보내준 영상에 when 쓰는 법 나와서 공부했는데 이르케 쓰이는 걸 보니 반갑따!!

2023-01-06 04:56 UTC, 0zlrlo requested changes

2023-01-06 04:56 UTC, 0zlrlo commented on app/src/main/res/layout/fragment_on_fourth.xml
> +
로그인, 회원가입 버튼을 만들어 주셔야 할 것 같습니다!

2023-01-06 07:32 UTC, DongjooSEO commented on app/src/main/res/drawable/img_onboarding_logoa.xml
> +  <path
피그마 내에서 다양한 버전의 로고 중 해당 로고가 a 번이라 뒤에 a 를 붙였습니다!

2023-01-08 17:25 UTC, b1urrrr requested changes
제약을 전반적으로 다시 설정해주어야할 것 같습니다!
xml 구현하는 김에 회원가입과 로그인 버튼 구현도 같이 해주시면 더 진행이 빠를 것 같습니다 :)
화이팅이에요!

2023-01-08 17:25 UTC, b1urrrr commented on app/src/main/AndroidManifest.xml
> +        </activity>
```suggestion
        <activity
            android:name="com.keyneez.presentation.onboarding.OnboardingActivity"
            android:exported="false"
            android:screenOrientation="portrait" />
```

태그 합치고 화면 회전 막아주세요!

2023-01-08 17:25 UTC, b1urrrr commented on app/build.gradle
> +    implementation "com.tbuonomo:dotsindicator:4.3"
다른 의존성과 헷갈리지 않게 위쪽으로 빼주시면 좋을 것 같아요!

2023-01-08 17:25 UTC, b1urrrr commented on app/src/main/java/com/keyneez/presentation/onboarding/adapter/OnboardingAdapter.kt
> +package com.keyneez.presentation.onboarding.adapter
adapter 패키지는 없어도 될 것 같은데 삭제하는 게 어떨까요?

2023-01-08 17:25 UTC, b1urrrr commented on app/src/main/res/layout/activity_onboarding.xml
> +            app:layout_constraintTop_toBottomOf="@id/btn_onboarding_signup" />
width가 match_parent로 이미 설정되어 있다면 constraintStart와 constraintEnd는 불필요한 코드인 것 같습니다! 
그리고 회원가입과 로그인 버튼이 화면 아래를 기준으로 위치하도록 제약을 다시 설정해주세요!

2023-01-08 17:25 UTC, b1urrrr commented on app/src/main/res/values/strings.xml
> +    //onboarding
```suggestion
    // onboarding
```

2023-01-08 17:25 UTC, b1urrrr commented on app/src/main/res/layout/activity_onboarding.xml
> +            app:layout_constraintTop_toBottomOf="@id/vp_onboarding" />
이 아이들을 회원가입, 로그인 버튼을 제외한 남은 공간에서 가운데에 위치하도록 제약을 설정해야 보기 예쁠 것 같다는 생각이 듭니다 🤔

2023-01-08 17:25 UTC, b1urrrr commented on app/src/main/res/layout/activity_onboarding.xml
> +            android:paddingHorizontal="8dp"
paddingHorizontal은 불필요한 코드인 것 같습니다~ 제거해주세요!

2023-01-08 17:25 UTC, b1urrrr commented on app/src/main/res/layout/activity_onboarding.xml
> +            android:paddingHorizontal="8dp"
이것도 제거해주세요!

2023-01-08 17:25 UTC, b1urrrr commented on app/src/main/res/layout/activity_onboarding.xml
> +            app:layout_constraintTop_toTopOf="parent" />
피그마의 onboarding 페이지에 있는 로고를 다시 가져와주세요.
현재 export 하신 로고는 크기가 맞지 않습니다!
onboarding 페이지의 로고를 src에 설정한 다음 height를 wrap_content로 설정해주세요

2023-01-08 17:25 UTC, b1urrrr commented on app/src/main/res/layout/activity_onboarding.xml
> +</layout>
![Screenshot_1673197871](https://user-images.githubusercontent.com/70993562/211209532-889de565-bbff-46b3-9d50-4f054ae14594.png)

결과는 이와 같은 모습이 될 것 입니다.

2023-01-08 17:25 UTC, b1urrrr commented on app/src/main/java/com/keyneez/presentation/onboarding/OnboardingActivity.kt
> +//        }
데이터바인딩으로 구현하면 간단하고 쉽지만...!
뷰에서 구현을 원하신다면 뷰페이저2의 registerOnPageChangeCallback 함수와 onPageSelected 함수의 사용법을 찾아보시는 것을 추천드립니다.

https://user-images.githubusercontent.com/70993562/211209952-b872ef1c-4868-40a6-b572-483614db80d9.mp4

2023-01-08 17:25 UTC, b1urrrr commented on app/src/main/res/drawable/shape_gray050_gary900line_4_rect.xml
> +</shape>
컨벤션에 맞게 shape drawable 네이밍 수정 부탁드립니다

2023-01-08 17:25 UTC, b1urrrr commented on app/src/main/res/values/themes.xml
> +<resources>
이건 왜 제거하신 건지 알 수 있을까요?

2023-01-09 12:34 UTC, DongjooSEO commented on app/src/main/res/values/themes.xml
> +<resources>
이거 사용안되어서 ctrl+alt +o 하면서 지워졌네요,,

2023-01-10 03:00 UTC, 0zlrlo approved these changes
우앙 고생하셨습니다!!! 온보팅 믓쪄~~

2023-01-10 10:37 UTC, b1urrrr approved these changes
LGTM!!!!!!

2023-01-10 10:51 UTC, merged