[UI/#17] id / id 뷰 구현
Keyneez/Keyneez-AOS pull request #21
Opened 2023-01-07 16:32 UTC by 0zlrlo

## 관련 이슈
- closed #17 

## 작업 내역
- task 기준 id 뷰, id photo 뷰 모두 구현하였습니다.

## PR 포인트
- 선택적으로 뜨는 건 true, false로 구분하여 뜨게끔 하였습니다.
- 바텀시트가 새 프래그먼트 쓴다고 생각을 안해서 따로 task에 넣지도 않았었는데 따로 프래그먼트를 만들어야 해서 만들었습니다.

## 실행 화면
경우의 수가 많아 내일 바로 보여드리겠습니다!

2023-01-07 22:44 UTC, b1urrrr requested changes
크으 이제 뷰를 진짜 잘 구현하시네요 👏👏❤️❤️
합숙하면서 열심히 달려봅시다 🏃‍♀️

2023-01-07 22:44 UTC, b1urrrr commented on app/src/main/java/com/keyneez/presentation/main/MainActivity.kt
> +                R.id.menu_card -> navigateTo<IdFragment>()
main_menu.xml에서 카드는 enable, clickable 속성을 false로 처리해놨기 때문에 클릭이 불가능한 상태입니다!
그냥 지워도 될 것 같아요

2023-01-07 22:44 UTC, b1urrrr commented on app/src/main/java/com/keyneez/presentation/main/id/IdBenefitFragment.kt
> +package com.keyneez.presentation.main.id
id 패키지에 있는 파일들을 좀 더 세분화해서 패키지 정리를 하면 좋을 것 같아요!

EX) 
dialog 패키지 : 바텀 시트 다이얼로그 프래그먼트들
photo 패키지 : IdPhotoActivity와 뷰모델

2023-01-07 22:44 UTC, b1urrrr commented on app/src/main/java/com/keyneez/presentation/main/id/IdBenefitFragment.kt
> +}
크으 바텀 시트 구현하시느라 고생하셨습니다 👏❤️
저도 나중에 구현할 때 참고해서 해야겠어요 🤭

2023-01-07 22:44 UTC, b1urrrr commented on app/src/main/java/com/keyneez/presentation/main/id/IdFragment.kt
> +        }
요 로직도 함수화를 하는 게 좋을 것 같아요!

2023-01-07 22:44 UTC, b1urrrr commented on app/src/main/java/com/keyneez/presentation/main/id/IdFragment.kt
>      }
main, content 보다 좀 더 이해하기 쉽게 네이밍하는 게 좋을 것 같아요! 
그리고 버튼 클릭 리스너는 `init???BtnClickListener` 요런 식이 좋을 것 같슴다

2023-01-07 22:44 UTC, b1urrrr commented on app/src/main/java/com/keyneez/presentation/main/id/IdPhotoActivity.kt
> +    val manager = supportFragmentManager
사용되지 않는 변수인 것 같네요! 왜 만들었는지 알 수 있을까요?
불필요한 변수라면 삭제해주세요

2023-01-07 22:44 UTC, b1urrrr commented on app/src/main/java/com/keyneez/presentation/main/id/IdPhotoActivity.kt
> +        }
이 로직도 함수화해주세요!
그리고 실물인증 버튼이 활성화되었다는 뜻은 OCR 인증을 마쳤다는 뜻이기 때문에 이에 대한 분기처리는 필요 없을 것 같습니다.

2023-01-07 22:44 UTC, b1urrrr commented on app/src/main/java/com/keyneez/presentation/main/id/IdPhotoActivity.kt
> +            if (true) {
생각해보니 실물인증 확인 시에 서버에서 이미지가 세로인지 가로인지 알 수 있는 정보가 받아져오는지 확인해야할 것 같습니다

2023-01-07 22:44 UTC, b1urrrr commented on app/src/main/java/com/keyneez/presentation/main/id/IdPhotoActivity.kt
> +    }
back 버튼을 누른 경우 프래그먼트를 띄우는 것이 아니라 IdPhoto 액티비티를 종료해야합니다! IdFragment와 관련된 로직은 삭제해주세요

2023-01-07 22:44 UTC, b1urrrr commented on app/src/main/java/com/keyneez/presentation/main/like/LikeViewModel.kt
>                  title = "청소년 \n영화관 할인"
```suggestion
                title = "청소년\n영화관 할인"
```

2023-01-07 22:44 UTC, b1urrrr commented on app/src/main/res/drawable/shape_black_fill_4_rect.xml
> +</layer-list>
```suggestion
<shape xmlns:android="http://schemas.android.com/apk/res/android"
    android:shape="rectangle">
    <solid android:color="@color/gray900" />
    <corners android:radius="4dp" />
</shape>
```
이 경우에는 shape만 있어도 될 것 같습니다! 같은 경우의 shape drawable 파일들을 수정해서 같이 코드량을 줄여봅시다
저도 수정하겠습니다 🙃

2023-01-07 22:44 UTC, b1urrrr commented on app/src/main/res/drawable/shape_white_fill_9_rect.xml
> +</layer-list>
네이밍에서 white를 사용한 파일들은 대신 gray050을 써주세요!

2023-01-07 22:44 UTC, b1urrrr commented on app/src/main/res/layout/activity_id_photo.xml
> +    </androidx.constraintlayout.widget.ConstraintLayout>
```suggestion
        <com.keyneez.util.custom.VerticalCardFrameView
            android:id="@+id/cfv_id_photo_vertical"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:layout_marginTop="103dp"
            android:background="@color/gray050_80" />
    </androidx.constraintlayout.widget.ConstraintLayout>
```
공백 제거 부탁드립니다!

2023-01-07 22:44 UTC, b1urrrr commented on app/src/main/res/layout/activity_id_photo.xml
> +            app:layout_constraintTop_toTopOf="parent" />
id값 추가 부탁드립니다!
height는 match_parent로 하고 scaleType을 centerCrop으로 하는 것이 좋을 것 같습니다

2023-01-07 22:44 UTC, b1urrrr commented on app/src/main/res/layout/activity_id_photo.xml
> +            android:background="@color/gray050_80" />
ocrActivity와 프레임뷰 크기가 같아야 할 것 같아서 marginTop을 28dp로 설정하고 뒤로가기와 타이틀이 있는 부분을 하얀색 레이아웃으로 하나 만들어주시면 좋을 것 같아요!

2023-01-07 22:44 UTC, b1urrrr commented on app/src/main/res/layout/bottomsheet_id_benefit.xml
> +<?xml version="1.0" encoding="utf-8"?>
저희 바텀시트 레이아웃은 bot_sheet을 붙이기로 해서 수정 부탁드립니다!

2023-01-07 22:44 UTC, b1urrrr commented on app/src/main/res/layout/bottomsheet_id_benefit.xml
> +        app:layout_behavior="com.google.android.material.bottomsheet.BottomSheetBehavior">
id에 layout 넣어주세요!

EX) layout_id_benefit

2023-01-07 22:44 UTC, b1urrrr commented on app/src/main/res/layout/bottomsheet_id_benefit.xml
> +                app:layout_constraintTop_toTopOf="@id/layout_id_benefit_museum" />
```suggestion
            <TextView
                android:id="@+id/tv_id_benefit_museum"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_marginTop="98dp"
                android:text="@string/id_museum_img"
                android:textColor="@color/gray900"
                android:textSize="53dp"
                app:layout_constraintEnd_toEndOf="@id/layout_id_benefit_museum"
                app:layout_constraintTop_toTopOf="@id/layout_id_benefit_museum" />
```
수정의 흔적이...!ㅋㅋㅋㅋㅋ

2023-01-07 22:44 UTC, b1urrrr commented on app/src/main/res/layout/bottomsheet_id_benefit.xml
> +            app:layout_constraintTop_toBottomOf="@id/layout_id_benefit_amusementpark">
constraint를 위 아래로 주니까 컴포넌트가 중앙으로 위치하게 되는 것 같습니다!
아래 제약과 marginBottom을 삭제하고 최상단 layout에 paddingBottom 설정 부탁드립니다

2023-01-07 22:44 UTC, b1urrrr commented on app/src/main/res/layout/bottomsheet_id_profile.xml
> +        app:layout_behavior="com.google.android.material.bottomsheet.BottomSheetBehavior">
id에 layout 붙여주세요!

2023-01-07 22:44 UTC, b1urrrr commented on app/src/main/res/layout/bottomsheet_id_profile.xml
> +            app:layout_constraintTop_toTopOf="parent" />
이 뷰는 로고에 대해 constraintTop_toBottomOf 제약을 주는 것이 좋을 것 같네요!

2023-01-07 22:44 UTC, b1urrrr commented on app/src/main/res/layout/bottomsheet_id_profile.xml
> +
얘도 bototm 제약과 marginBottom 을 지우고 최상단 레이아웃에 paddingBottom을 주는 게 좋을 것 같습니다! 그리고 topConstraint는 생일에 주도록 수정 부탁드려요 🙃
밑에 빈 줄도 지워주세요!

2023-01-07 22:44 UTC, b1urrrr commented on app/src/main/res/layout/fragment_id.xml
> +            app:layout_constraintTop_toTopOf="parent">
위아래 제약을 parent로 주니까 bottom navigation bar의 높이는 고려가 되지 않는 것 같아요🥲 다른 방법으로 위아래 제약을 설정해주세요!
(layout_id_main도 마찬가지입니다!)

그리고 content와 main이라는 네이밍보다 좀 더 직관적이고 이해가 쉬운 네이밍이 있으면 좋을 것 같습니다.... 뭐가 좋을까요

2023-01-07 22:44 UTC, b1urrrr commented on app/src/main/res/layout/fragment_id.xml
> +                android:id="@+id/tv_id_main_semititle"
```suggestion
                android:id="@+id/tv_id_main_semi_title"
```
별 거 아니지만... 안스에서 밑줄 안 쳐지는 네이밍이 보기 편하더라고요 ㅋㅋㅋㅋㅋ

2023-01-07 22:44 UTC, b1urrrr commented on app/src/main/res/layout/fragment_id.xml
> +                app:layout_constraintTop_toBottomOf="@id/tv_id_main_semititle" />
padding 4dp를 준 다음에 marginStart로 간격을 조정해주세요!
`constraintBottom_toBottomOf="이름 텍스트뷰"`도 해줘야 항상 이름의 가운데에 버튼이 위치할 것 같습니다!

2023-01-07 22:44 UTC, b1urrrr commented on app/src/main/res/layout/fragment_id.xml
> +                app:layout_constraintStart_toStartOf="@id/iv_id_main_background" />
제약을 Bottom으로 주기보다 이름에 대해 Top 제약을 주는 게 좋아보입니다!

2023-01-08 00:41 UTC, b1urrrr commented on app/src/main/java/com/keyneez/presentation/main/id/IdPhotoActivity.kt
> +class IdPhotoActivity : BindingActivity<ActivityIdPhotoBinding>(R.layout.activity_id_photo) {
```
private fun initCameraFrameView() {
        binding.cfvOcrVertical.setLayerType(View.LAYER_TYPE_SOFTWARE, null)
        binding.cfvOcrHorizontal.setLayerType(View.LAYER_TYPE_SOFTWARE, null)
    }
```
CameraFrameView는 위와 같이 레이어 타입을 액티비티에서 설정해주어야 프레임의 카드 모양 구멍이 투명하게 잘 보입니다! 추가 부탁드려요 :)

2023-01-08 05:24 UTC, DongjooSEO approved these changes
와웅,, 넘 고생해써요 
합숙 잘 달려보자구~~~

2023-01-08 05:24 UTC, DongjooSEO commented on app/src/main/java/com/keyneez/presentation/main/id/IdBenefitFragment.kt
> +class IdBenefitFragment : BottomSheetDialogFragment() {
바텀시트 구현한 지은이 넘 멋있다아,, 😎

2023-01-08 17:46 UTC, b1urrrr approved these changes
몇 가지 요청드린 부분만 수정하신 다음에 머지해주세요 😉 (믿고 approve 드립니당)

1. 이모지 이미지들은 사용하지 않으니 삭제해도 될 것 같아요 ㅎㅎ
2. 카드 이미지 추가한 후에 젤리나 카드 이미지뷰 크기를 조정해야할 것 같습니다! 나중에 같이 조정해봐요~

2023-01-08 17:46 UTC, b1urrrr commented on app/src/main/java/com/keyneez/presentation/main/id/IdFragment.kt
> +    }
getIds라는 네이밍은 서버에서 Id를 받아오는 GET 통신 함수로 헷갈릴 것 같아요 🥲 다른 좋은 네이밍 있을까요?!

EX) initIdView, initIdLayout ....

2023-01-08 17:46 UTC, b1urrrr commented on app/src/main/java/com/keyneez/presentation/main/id/IdPhotoActivity.kt
> +    }
다음에 한번 데이터바인딩으로 바꾸는 법 알려드릴게요!! 👍👍

2023-01-08 17:46 UTC, b1urrrr commented on app/src/main/java/com/keyneez/presentation/main/id/dialog/IdProfileFragment.kt
> +    }
혹시 이 부분 클릭 잘 되나요?
제 에뮬레이터로 돌려보니 액티비티 실행이 안 되네요 🥲

2023-01-09 07:04 UTC, closed without merging