[UI/#20] info detail 레이아웃 구현
Keyneez/Keyneez-AOS pull request #24
Opened 2023-01-08 09:47 UTC by DongjooSEO

## 관련 이슈
- closed #20 

## 작업 내역
- 상세 뷰 레이아웃 구현

## PR 포인트
- 스크롤뷰 사용법 맞는 지
-  상세 뷰 중 keyword는 홈 뷰 머지한 후 수정하겠습니다.

## 실행 화면
![image](https://user-images.githubusercontent.com/83579348/211189639-d853d3a6-b14a-4de6-8265-53481fe1af69.png)

2023-01-08 14:08 UTC, 0zlrlo requested changes
와아 고생 많이 한 게 느껴져요!! 너무 고생했어요🥲❤️

2023-01-08 14:08 UTC, 0zlrlo commented on app/src/main/res/drawable/shape_gray050_gary900line_4_rect.xml
> +<?xml version="1.0" encoding="utf-8"?>
이름을 형식에 맞게 고쳐주세요!

2023-01-08 14:08 UTC, 0zlrlo commented on app/src/main/res/drawable/shape_rect_fill_gray500.xml
> +<?xml version="1.0" encoding="utf-8"?>
위와 같이 이름을 형식에 맞춰 바꿔주세용!

2023-01-08 18:14 UTC, b1urrrr requested changes
고생하셨습니다!!
중복되는 코리는 달지 않았는데 전반적인 코드를 훑어보면서 고칠 부분들은 고쳐주세요!

2023-01-08 18:14 UTC, b1urrrr commented on app/src/main/AndroidManifest.xml
> +        </activity>
activity 태그 하나로 합치고 화면 회전 막아주세요!

2023-01-08 18:14 UTC, b1urrrr commented on app/src/main/java/com/keyneez/presentation/main/detail/DetailActivity.kt
> +    }
```suggestion
    /** 뒤로가기 버튼 */
    private fun initBackClickListener() {
        binding.btnDetailBack.setOnSingleClickListener { }
    }

    /** 공유 버튼 */
    private fun initShareClickListener() {
        binding.btnDetailShare.setOnSingleClickListener { }
    }

    /** 좋아요 버튼 */
    private fun initHeartClickListener() {
        binding.btnDetailHeart.setOnSingleClickListener { }
    }
```

/** 주석 */ 를 활용하여 함수에 대한 주석을 남기면 다른 파일에서 함수 사용 시에 미리보기에 주석에 써놓은 설명이 보인답니다!
그런데 지금 만드신 함수들은 네이밍만으로 어떤 함수인지 파악이 잘 되기 때문에 주석이 불필요해보이긴 하네요

2023-01-08 18:14 UTC, b1urrrr commented on app/src/main/res/drawable/shape_rect_fill_gray800_100.xml
> +<?xml version="1.0" encoding="utf-8"?>
전반적으로 drawable 파일들 네이밍이 잘 되어 있는지 확인하고 수정해주세요!

2023-01-08 18:14 UTC, b1urrrr commented on app/src/main/res/layout/activity_home_detail.xml
> +            android:id="@+id/detail_layout"
```suggestion
            android:id="@+id/layout_detail"
```

2023-01-08 18:14 UTC, b1urrrr commented on app/src/main/res/layout/activity_home_detail.xml
> +        android:id="@+id/detail_scroll_layout"
```suggestion
        android:id="@+id/scroll_detail"
```
id 값 컨벤션 확인해주세요!

2023-01-08 18:14 UTC, b1urrrr commented on app/src/main/res/layout/activity_home_detail.xml
> +                app:layout_constraintTop_toTopOf="parent" />
요 아이는 왼쪽이 아니라 오른쪽에 붙어있어야 하는 버튼이기 때문에 constraintStart 제약은 지워주시고 constraintEnd 제약을 추가해주세요~

2023-01-08 18:14 UTC, b1urrrr commented on app/src/main/res/layout/activity_home_detail.xml
> +                app:layout_constraintTop_toTopOf="parent" />
constraintStart와 marginStart는 불필요한 속성인 것 같습니다!!
지워주세요!

2023-01-08 18:14 UTC, b1urrrr commented on app/src/main/res/layout/activity_home_detail.xml
> +                app:layout_constraintTop_toBottomOf="@id/btn_detail_back" />
피그마 참고하셔서 shape drawable을 만들어 background에 적용해주시고, text는 Alt + Enter로 strings.xml에 추가해주세요

2023-01-08 18:14 UTC, b1urrrr commented on app/src/main/res/layout/activity_home_detail.xml
> +                app:layout_constraintTop_toBottomOf="@id/btn_detail_back" />
그리고 marginStart 31dp가 아닌 것 같습니다.
피그마 꼼꼼하게 봐주세요!!

2023-01-08 18:14 UTC, b1urrrr commented on app/src/main/res/layout/activity_home_detail.xml
> +
인포 탭 상세 페이지에 카드 이미지뷰가 있어야할 것 같습니다!
추가해주세요

2023-01-08 18:14 UTC, b1urrrr commented on app/src/main/res/layout/activity_home_detail.xml
> +                android:layout_marginHorizontal="24dp"
23dp인 것 같습니다

2023-01-08 18:14 UTC, b1urrrr commented on app/src/main/res/layout/activity_home_detail.xml
> +                android:layout_marginTop="8dp"
자세히 보시면 8dp가 아닌 9.5dp로 피그마에 나와있는데, 소수점은 적당히 처리해서 10dp로 넣어주시면 될 것 같습니다.

2023-01-08 18:14 UTC, b1urrrr commented on app/src/main/res/layout/activity_home_detail.xml
> +                android:text="2023 아트페어"
string 모두 다 추가해주세요
중복되는 코리는 달지 않아도 알아서 수정해주세요!

2023-01-08 18:14 UTC, b1urrrr commented on app/src/main/res/layout/activity_home_detail.xml
> +                app:layout_constraintTop_toTopOf="parent" />
여기서는 height를 wrap_content로 하셔도 될 것 같네요!!
그리고 이미지뷰의 제약은 기간 텍스트뷰에 설정하는 것이 좋을 것 같습니다.

2023-01-08 18:14 UTC, b1urrrr commented on app/src/main/res/layout/activity_home_detail.xml
> +                app:layout_constraintStart_toStartOf="parent"
너비가 match_parent면 constraintStart와 constraintEnd는 제거해도 되겠죠?

2023-01-08 18:14 UTC, b1urrrr commented on app/src/main/res/layout/activity_home_detail.xml
> +                app:drawableEndCompat="@drawable/ic_detail_forward" />
오오 좋은 속성 알아갑니다!!

2023-01-08 18:14 UTC, b1urrrr commented on app/src/main/res/layout/activity_home_detail.xml
> +                android:text="활동소개활동소개활동소개활동소개
이런 더미 데이터는 tools:text를 활용해주세요

2023-01-08 18:14 UTC, b1urrrr commented on app/src/main/res/layout/activity_home_detail.xml
> +                app:layout_constraintTop_toBottomOf="@id/tv_detail_benefit_title" />
이런 건 이미지뷰가 아니라 View로 구현해주세요!!
width는 match_parent로 설정한 다음 제약을 적당히 설정해줘야할 것 같습니다

2023-01-08 18:14 UTC, b1urrrr commented on app/src/main/res/layout/activity_home_detail.xml
> +                android:src="@drawable/ic_detail_heart"
하트는 selector로 구현해야할 것 같습니다.
채워진 하트는 피그마 왼쪽에서 확인해주세요!

2023-01-10 03:07 UTC, 0zlrlo approved these changes
앗 여기서 셀렉터를 했군요ㅎㅎㅎ너무 고생했어용!! 숙소에서 봅시당!!

2023-01-10 13:16 UTC, b1urrrr approved these changes
LGTM👍
고생하셨습니다!

2023-01-10 13:17 UTC, merged