[UI/#26] setting / 설정 뷰 구현하기
Keyneez/Keyneez-AOS pull request #27
Opened 2023-01-08 16:49 UTC by 0zlrlo

## 관련 이슈
- closed #26 

## 작업 내역
- 설정 뷰 구현하였습니다.
- 아이디 뷰 조금 수정하였습니다.

## PR 포인트
- 

## 실행 화면
<img width="377" alt="스크린샷 2023-01-09 오전 1 48 32" src="https://user-images.githubusercontent.com/99941493/211208710-30d8116f-c37b-40b6-98a9-2cb21491b935.png">

2023-01-08 18:50 UTC, b1urrrr requested changes
설정 뷰 구현 감사해요 ❤️❤️

2023-01-08 18:50 UTC, b1urrrr commented on app/src/main/res/layout/fragment_setting.xml
> +            app:layout_constraintTop_toBottomOf="@id/tv_setting_log_out" />
로그아웃, 회원탈퇴에도 padding 12dp 주세요!

2023-01-09 06:24 UTC, b1urrrr approved these changes
LGTM 😉👍

2023-01-09 07:38 UTC, DongjooSEO approved these changes
빠르게 만들어냈네!! 넘 고생해써

2023-01-09 07:38 UTC, merged