[MOD/#77] search/ 코드 수정 및 기능 추가
Keyneez/Keyneez-AOS pull request #82
Opened 2023-03-16 14:09 UTC by 0zlrlo

## 관련 이슈
- closed #77

## 작업 내역
-검색 결과 0개면 토스트 띄우기
-엔터 누르면 검색되도록 수정
-긴 문자열 입력 시 검색 버튼 오른쪽에 문자 보이는 거 수정
-이미지버튼 background 투명하게 수정
## PR 포인트

## 실행 화면

2023-03-16 16:13 UTC, b1urrrr requested changes
고생하셨습니다!
key event와 관련된 처리 잘 보고 갑니다 🤭

2023-03-16 16:13 UTC, b1urrrr commented on app/src/main/java/com/keyneez/presentation/main/search/SearchActivity.kt
> +            }
하드코딩 말고 strings에 넣어서 코딩해주세요!
그리고 toast는 확장 함수로 만들어놓은 함수 사용해주세요~

2023-03-16 16:13 UTC, b1urrrr commented on app/src/main/java/com/keyneez/presentation/main/search/SearchActivity.kt
> +    }
`setupSearchData()`는 onCreate에서 이미 호출되고 있는데 다른 함수들에서 중복되어서 다시 호출되고 있네요! 
livedata를 observe한다는 게 무슨 의미인지 한번 찾아보셨으면 좋겠어요 :)

2023-03-16 16:13 UTC, b1urrrr commented on app/src/main/java/com/keyneez/presentation/main/search/SearchActivity.kt
SearchActivity 상단에 선언 되어 있는 data 변수는 언제 사용되고 있는 건가요?
(해당 코드에 코리를 달 수 없어 여기에 적습니다.)

2023-03-16 16:13 UTC, b1urrrr commented on app/src/main/java/com/keyneez/presentation/main/search/SearchActivity.kt
>      private fun observeSearchStateMessage() {
컨벤션에 맞게 setup___ 로 함수명을 네이밍해주세요!

2023-03-16 16:13 UTC, b1urrrr commented on app/src/main/res/layout/fragment_id.xml
>              android:id="@+id/layout_id_main"
View로 구현한 컴포넌트는 id를 view___로 네이밍하는 게 더 적합할 것 같습니다!
xml id 컨벤션 한번 정독하시는 걸 추천드릴게요 :)
(이것 또한 해당 코드에 코리를 달 수 없어 여기에 적습니다.)

2023-03-16 16:13 UTC, b1urrrr commented on app/src/main/res/layout/activity_search.xml
> +            android:background="@android:color/transparent"
혹시 이렇게 바꾼 이유가 뭔가요?

2023-03-18 02:51 UTC, 0zlrlo commented on app/src/main/java/com/keyneez/presentation/main/search/SearchActivity.kt
> +            }
Toast.makeText(getActivity(), "성공하셨습니다.", Toast.LENGTH_SHORT).show() <- ocrResult에서 사용한 토스트 코드입니다! 이것처럼 다른 코드들 보니까 토스트를 이렇게 사용했던데 확장함수를 이용하려면 어떻게 해야 할까요? 알려주시면 감사하겠습니다!

2023-03-18 02:53 UTC, 0zlrlo commented on app/src/main/java/com/keyneez/presentation/main/search/SearchActivity.kt
> +    }
중복되어서 호출한 이유는 검색버튼을 눌렀을 때도 검색이 되고, 엔터를 눌렀을 때도 검색이 되게끔 하고 싶어 그 두가지 기능을 다 구현하였기 때문에 중복 호출을 하였습니다..! 혹시 다른 방법을 알려주실 수 있나용??

2023-03-18 03:40 UTC, 0zlrlo commented on app/src/main/res/layout/activity_search.xml
> +            android:background="@android:color/transparent"
바탕을 투명색으로 바꾸기 위해 검색 후 저렇게 고쳤습니다!

2023-03-18 03:40 UTC, 0zlrlo commented on app/src/main/java/com/keyneez/presentation/main/search/SearchActivity.kt
엇 지금 확인해 보니 사용하고 있지 않네요! 지우겠습니당

2023-03-18 15:04 UTC, b1urrrr commented on app/src/main/java/com/keyneez/presentation/main/search/SearchActivity.kt
> +            }
https://github.com/Keyneez/Keyneez-AOS/blob/develop/app/src/main/java/com/keyneez/presentation/ocr/guide/guide/OcrGuideFragment.kt#L53

https://github.com/Keyneez/Keyneez-AOS-Lab/pull/15#discussion_r1059779480

다른 코드와 이전 코드리뷰 참고 부탁드립니다! 
데모데이 직전에 급하게 구현하면서 빠트린 부분이 있었나보네요 😅
저도 수정하겠습니다!

2023-03-18 15:05 UTC, b1urrrr commented on app/src/main/java/com/keyneez/presentation/main/search/SearchActivity.kt
> +    }
observe하는 함수는 초기에 한번만 호출해주어도 정상적으로 작동할 겁니다!
livedata와 observe 개념을 조금 더 찾아보시고 그래도 이해가 안 가시면 알려주세요!

2023-03-18 15:07 UTC, b1urrrr commented on app/src/main/res/layout/activity_search.xml
> +            android:background="@android:color/transparent"
`@null`로 지정해도 아이콘 배경이 투명하게 설정된다고 알고 있었는데 아니었나요?

2023-03-18 15:09 UTC, b1urrrr commented
커밋하실 때 "코드 리뷰 반영" 보다는 어떤 로직을 수정했는지 구체적으로 명시해주시는 게 유지보수나 형상 관리 측면에서 도움이 될 것 같습니다!

EX) 함수 네이밍 컨벤션 반영

2023-03-18 16:04 UTC, 0zlrlo commented on app/src/main/res/layout/activity_search.xml
> +            android:background="@android:color/transparent"
앗 의미적으로만 다르고 동일시 되는 거 같습니다. 아래 글처럼 null이 더 좋다고 하여 다시 바꾸었습니다!
https://stackoverflow.com/questions/9311123/is-there-any-diff-null-vs-00000000

2023-03-18 20:07 UTC, b1urrrr approved these changes
LGTM 💚

2023-03-18 20:07 UTC, b1urrrr commented on app/src/main/java/com/keyneez/presentation/main/search/SearchActivity.kt
> +            if (it.size.toString() == "0") {
it.size == 0으로 하면 안 되나요?

2023-03-18 20:07 UTC, b1urrrr commented on app/src/main/res/drawable/shape_gray200_fill_bot14_rect.xml
> +</shape>
지금 봤는데 shape 파일 네이밍 센스 있게 잘 하셨네요 👍👍

2023-03-19 03:41 UTC, 0zlrlo commented on app/src/main/java/com/keyneez/presentation/main/search/SearchActivity.kt
> +            if (it.size.toString() == "0") {
가능해요!! 수정하였습니다

2023-03-19 08:18 UTC, DongjooSEO approved these changes
LGTM❤️❤️
넘 수고 많았어요

2023-03-19 08:20 UTC, merged